#!/usr/bin/php
#
# pull 之後, 自動執行 autorun.php shell
#
#   install
#       - cp ./shell/git-hooks/post-merge ./.git/hooks/
#       - chmod +x ./.git/hooks/*
#
#   預計還要處理
#       - 非根目錄下的路徑問題
#

/usr/bin/php ./autorun.php